# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: |
        sudo apt update
        sudo apt install jq -y

      - run: |
        git config --local user.email "melvin.vermeer@gmail.com"
        git config --local user.name "Melvin Vermeer [ci]"
        jq --arg version ${GITHUB_REF#refs/tags/} '.version = $version' package.json > package.json.tmp
        mv package.json.tmp package.json
        git add package.json
        git commit --no-verify -m "update package version ${GITHUB_REF#refs/tags/} [skip ci]"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - run: git push --no-verify
